---
title: आकृतियों का उपयोग करके बैकड्रॉप और स्प्राइट बनाएं
hero_image: images/banner.png
description: scratch3-backdrops-and-sprites-using-shapes description
version: 4
listed: false
copyedit: false
last_tested: "2021-03-10"
steps:
  - title: आकृतियों का उपयोग करके बैकड्रॉप और स्प्राइट बनाएं
