---
title: 'Yenza umfanekiso wangasemva neziSprite usebenzia iimilo (imizekelo yemilo: isangqa, uxande, unxantathu njalo njalo)'
hero_image: images/banner.png
description: ingcaciso ka scratch3-imifanekiso-yangasemva-kunye-neziSprite-usebenzisa-iimilo
version: 4
listed: false
copyedit: false
last_tested: "2021-03-10"
steps:
  - title: 'Yenza umfanekiso wangasemva neziSprite usebenzia iimilo (imizekelo yemilo: isangqa, uxande, unxantathu njalo njalo)'
