---
title: 図形を使って背景とスプライトを作成する
hero_image: images/banner.png
description: scratch3-backdrops-and-sprites-using-shapes 説明
version: 4
listed: false
copyedit: false
last_tested: "2021-03-10"
steps:
  - title: 図形を使って背景とスプライトを作成する
