---
title: Hintergründe und Figuren mit Formen erstellen
hero_image: images/banner.png
description: scratch3-backdrops-and-sprites-using-shapes description
version: 4
listed: false
copyedit: false
last_tested: "2021-03-10"
steps:
  - title: Hintergründe und Figuren mit Formen erstellen
