---
title: Crea fondos y objetos usando formas
hero_image: images/banner.png
description: descripción scratch3-fondos-y-objetos-usando-formas
version: 4
listed: false
copyedit: false
last_tested: "2021-03-10"
steps:
  - 
    title: Crea fondos y objetos usando formas
