---
title: قم بإنشاء الخلفيات والكائنات باستخدام الأشكال
hero_image: images/banner.png
description: "scratch3- خلفيات الشاشة - الكائنات - تستخدم وصف الاشكال\nbackdrops-and-sprites-using-الأشكال الوصف"
version: 4
listed: false
copyedit: false
last_tested: "2021-03-10"
steps:
  - 
    title: قم بإنشاء الخلفيات والكائنات باستخدام الأشكال
