---
title: Twórz tła i duszki za pomocą kształtów
hero_image: images/banner.png
description: scratch3-backdrops-and-sprites-using-shapes opis
version: 4
listed: false
copyedit: false
last_tested: "2021-03-10"
steps:
  - title: Twórz tła i duszki za pomocą kształtów
