---
title: Skapa bakgrunder och sprajter med former
hero_image: images/banner.png
description: scratch3-bakgrunder och sprajter med former beskrivning
version: 4
listed: false
copyedit: false
last_tested: "2021-03-10"
steps:
  - title: Skapa bakgrunder och sprajter med former
