---
title: Δημιουργήστε σκηνικά και sprites χρησιμοποιώντας σχήματα
hero_image: images/banner.png
description: Δημιουργήστε σκηνικά και sprites χρησιμοποιώντας σχήματα
version: 4
listed: false
copyedit: false
last_tested: "2021-03-10"
steps:
  - title: Δημιουργήστε σκηνικά και sprites χρησιμοποιώντας σχήματα
