---
title: Δημιούργησε υπόβαθρα και αντικείμενα χρησιμοποιώντας σχήματα
hero_image: images/banner.png
description: scratch3-υπόβαθρα-και-αντικείμενα-χρησιμοποιώντας-σχήματα περιγραφή
version: 4
listed: false
copyedit: false
last_tested: "2021-03-10"
steps:
  - 
    title: Δημιούργησε υπόβαθρα και αντικείμενα χρησιμοποιώντας σχήματα
