---
title: Créer des arrière-plans et des sprites à l'aide de formes
hero_image: images/banner.png
description: description scratch3-arriereplans-et-sprites-utilisant-formes
version: 4
listed: false
copyedit: false
last_tested: "2021-03-10"
steps:
  - 
    title: Créer des arrière-plans et des sprites à l'aide de formes
