---
title: Crea sfondi e immagini usando le forme
hero_image: images/banner.png
description: scratch3-backdrops-and-sprites-using-shapes descrizione
version: 4
listed: false
copyedit: false
last_tested: "2021-03-10"
steps:
  - title: Crea sfondi e immagini usando le forme
